### ISSUE TITLE
Consider using the promise API

### ISSUE THREAD

**Issue by roberttod** [QubitProducts/sync-p#2]
I know the promise API is all classy-statey-non-functional, the `new` keyword makes me sad but maybe it would be good to do it that way just because it is nice sometimes to slot in a module like this where native promises or some other library have been used before. (though I guess when also doesn't really conform either)

Another advantage would be that you don't have to learn or lookup different docs if you know the way to use native promises.

@alanclarke, @jimmed what do you think?

**Comment by alanclarke** [comment]
So, if you use the new keyword, it works exactly the same... its optional!

**Comment by alanclarke** [comment]
```js
var Promise = require('sync-p')
Promise.all = require('sync-p/all')

return Promise.all([new Promise(function (resolve, reject) {
   resolve(123)
})])
```

**Comment by roberttod** [comment]
Sweet, maybe we should document it this way or include this in the docs.
